# Generated by Django 3.1.1 on 2020-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200922_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='flat_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
