# Generated by Django 3.1.1 on 2020-09-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_read_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='read_users',
        ),
    ]
