# Generated by Django 3.1.2 on 2020-10-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0005_auto_20201010_0544'),
        ('orders', '0010_order_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='controlpanel.client'),
        ),
    ]
