# Generated by Django 3.1.2 on 2020-10-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_exists',
            field=models.BooleanField(default=False),
        ),
    ]
