# Generated by Django 3.1.2 on 2020-10-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReadOrder',
        ),
    ]
