# Generated by Django 3.1.2 on 2020-10-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
