# Generated by Django 3.1.2 on 2020-10-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0004_client_total_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-total_orders',), 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
